schema: '**/*.graphqls'
schemaEntrypoint: 'src/apollo/server/types/todo.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
